# Generated by Django 5.1.1 on 2024-09-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumpost",
            name="blog_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="blogapp.post"
            ),
        ),
    ]
