# Generated by Django 5.1.1 on 2024-09-27 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_premiumpost_blog_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="premiumpost",
            name="blog_post",
        ),
        migrations.RemoveField(
            model_name="premiumpost",
            name="premium_content",
        ),
        migrations.AddField(
            model_name="premiumpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="premium_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="premiumpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="premiumpost",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="premiumpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="premiumpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
