# Generated by Django 5.1.1 on 2024-09-27 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_auto_20240927_0735"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="premium_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="premiumpost",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="premiumpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="premiumpost",
            name="title",
            field=models.CharField(default="Untitled Premium Post", max_length=200),
        ),
        migrations.AlterField(
            model_name="premiumpost",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
