# Generated by Django 5.1.1 on 2024-10-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0008_rename_date_added_comment_created_at_and_more"),
        ("blogapp", "0009_alter_comment_author"),
    ]

    operations = []
